spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/habsidadb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

cors:
  allowed-origins:
    http://localhost:5173,
    http://localhost:5174