spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/habsidadb
    username: postgres
    password: root

jwt:
  secret: dev-secret-key-for-local-testing-only-1234567890
  expiration: 86400000